/*
 * File: app/store/ShopListStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.ShopListStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ShopListStore',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                actionMethods: {
                    create: 'POST',
                    read: 'POST',
                    update: 'POST',
                    destroy: 'POST'
                },
                url: '/Manage/ShopList',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            fields: [
                {
                    name: 'shopId'
                },
                {
                    name: 'shopName'
                },
                {
                    name: 'userId'
                },
                {
                    name: 'typeId'
                },
                {
                    name: 'typeIds'
                },
                {
                    name: 'typeNames'
                },
                {
                    name: 'address'
                },
                {
                    name: 'areaId'
                },
                {
                    name: 'status'
                },
                {
                    name: 'addtime'
                },
                {
                    name: 'opentime'
                },
                {
                    name: 'adduser'
                },
                {
                    name: 'modifytime'
                },
                {
                    name: 'modifyuser'
                },
                {
                    name: 'introduction'
                },
                {
                    name: 'weixincode'
                },
                {
                    name: 'squre'
                },
                {
                    name: 'representproducts'
                },
                {
                    name: 'pricerange'
                },
                {
                    name: 'favorabledeals'
                },
                {
                    name: 'username'
                },
                {
                    name: 'piclist'
                },
                {
                    name: 'picdetail'
                },
                {
                    name: 'piclogo'
                }
            ]
        }, cfg)]);
    }
});