/*
 * File: app/store/TypeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TypeStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TypeStore',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                actionMethods: {
                    create: 'POST',
                    read: 'POST',
                    update: 'POST',
                    destroy: 'POST'
                },
                url: '/Home/TypeGet',
                reader: {
                    type: 'json',
                    root: 'data',
                    totalProperty: 'totalN'
                }
            },
            fields: [
                {
                    name: 'typeId'
                },
                {
                    name: 'typeName'
                },
                {
                    name: 'fatherId'
                },
                {
                    name: 'note'
                }
            ]
        }, cfg)]);
    }
});