/*
 * File: app/view/ChartPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ChartPanel', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar'
    ],

    height: 451,
    id: 'ChartPanel',
    width: 570,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: '累積実績照会',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'form',
                    flex: 1,
                    margins: '',
                    dock: 'top',
                    height: 77,
                    margin: '0 0 5 0',
                    layout: {
                        type: 'column'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'triggerfield',
                            margin: '0 0 10 0',
                            width: 246,
                            fieldLabel: '累積実績照会',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'datefield',
                            margin: '0 0 10 0',
                            width: 202,
                            fieldLabel: '計上年月',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 10 0',
                            width: 247,
                            fieldLabel: '取引先コード',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 10 0',
                            width: 207,
                            fieldLabel: '管理区分',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 10 0',
                            width: 246,
                            fieldLabel: '国内海外区分',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 10 0',
                            width: 209,
                            fieldLabel: 'タイトルNo.',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 20',
                            width: 76,
                            text: 'Search'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    margins: '0 0 5 0',
                    height: 168,
                    store: 'cResultVStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'yearM',
                            text: '年月'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'dealD',
                            text: '処理期'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'LDNO',
                            text: 'LD-NO'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'titleId',
                            text: 'タイトルNo.'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'zf',
                            text: '枝番'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ysFlag',
                            text: '印税区分'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'titleName',
                            text: 'タイトル名'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ljM',
                            text: '累計対象枚数'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ljwj',
                            text: '累計未払い金額'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ljfj',
                            text: '累計印税発生金額',
                            flex: 1
                        }
                    ],
                    listeners: {
                        select: {
                            fn: me.onGridpanelSelect,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    height: 169,
                    autoScroll: true,
                    items: [
                        {
                            xtype: 'chart',
                            height: 230,
                            itemId: 'ResultChart',
                            width: 600,
                            animate: true,
                            insetPadding: 20,
                            store: 'CarChartStore',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'name'
                                    ],
                                    position: 'left',
                                    title: ''
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'rating'
                                    ],
                                    position: 'bottom',
                                    title: '累積金額 '
                                }
                            ],
                            series: [
                                {
                                    type: 'bar',
                                    label: {
                                        display: 'insideEnd',
                                        field: 'rating',
                                        color: '#333',
                                        'text-anchor': 'middle'
                                    },
                                    axis: 'bottom',
                                    xField: 'name',
                                    yField: 'rating'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelSelect: function(rowmodel, record, index, eOpts) {
        //var detailPanel = this.child('#detailPanel');
        // update the detailPanel with data
        // this will trigger the tpl to become updates
        //detailPanel.update(record.data);

        var chart = this.down('#ResultChart');
        // get the quality field out of this record
        var qualityData = record.get('quality');
        chart.store.loadData(qualityData);
    }

});