/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.HomePanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.HomePanel',

    requires: [
        'Ext.XTemplate'
    ],

    border: false,
    id: 'HomePanel',
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: false,
                    id: 'HomeTab',
                    autoScroll: true,
                    title: 'ホーム',
                    items: [
                        {
                            xtype: 'dataview',
                            id: 'ShortCut',
                            itemId: 'ShortCut',
                            tpl: [
                                '<tpl for=".">',
                                '<div class="dataview-multisort-item" style="float:left;padding:8px;margin:8px;height:180px;">',
                                '    <div style="position:relative;width:80px;height:80px;">',
                                '     <img src="{url}{thumb}" width="80" height="80" />',
                                '    </div>',
                                '    <h3 style="width:90px; white-space:normal;">{name}</h3>',
                                '</div>',
                                '</tpl>'
                            ],
                            itemSelector: 'div.thumb-wrap',
                            store: 'HomeIcomStore'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});