/*
 * File: app/view/LoginWin.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginwin',

    height: 156,
    width: 317,
    layout: {
        type: 'fit'
    },
    closable: false,
    title: '登陆',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '用户名',
                            name: 'username',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '密码',
                            name: 'password',
                            inputType: 'password',
                            allowBlank: false
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'center',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    scale: 'medium',
                                    text: '登陆',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var form = this.down('form').getForm();
        if(form.isValid()){
            form.submit({
                clientValidation: true,
                url: '/Manage/Login',
                scope:this,
                success: function(form, action) {
                    Ext.util.Cookies.set('username',form.getValues().username);
                    Ext.ComponentQuery.query('[id=name]')[0].setText(form.getValues().username);
                    this.close();
                },
                failure: function(form, action) {
                    Ext.Msg.alert('提示',action.result.msg);
                }
            });
        }
    }

});