/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.HomePanel'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    border: false,
                    frame: true,
                    height: 35,
                    itemId: 'LogoPanel',
                    bodyStyle: 'background-color:#445D73;',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            id: 'basicToolBar',
                            itemId: 'basicToolBar',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnHome',
                                    itemId: 'btnHome',
                                    icon: 'data/img/home.png',
                                    tooltip: 'Home'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'image',
                                    height: 16,
                                    width: 16,
                                    src: 'data/img/user.png'
                                },
                                {
                                    xtype: 'label',
                                    text: '您好'
                                },
                                {
                                    xtype: 'label',
                                    id: 'name',
                                    margin: '0 5 0 0 ',
                                    text: '游客'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    id: 'logoff',
                                    icon: 'data/img/login.png',
                                    text: '注销',
                                    listeners: {
                                        click: {
                                            fn: me.onLogoffClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'treepanel',
                    region: 'west',
                    split: true,
                    width: 155,
                    collapseFirst: false,
                    collapsed: false,
                    collapsible: true,
                    title: '菜单',
                    titleCollapse: false,
                    root: {
                        expanded: true,
                        children: [
                            {
                                text: '商铺',
                                id: 'm1_1',
                                expanded: true,
                                children: [
                                    {
                                        text: '商铺管理',
                                        id: 'm1_1_1',
                                        leaf: true
                                    },
                                    {
                                        text: '首页广告',
                                        id: 'm1_1_3',
                                        leaf: true
                                    },
                                    {
                                        text: '推荐商铺',
                                        id: 'm1_1_2',
                                        leaf: true
                                    },
                                    {
                                        text: '商铺类型',
                                        id: 'm1_1_4',
                                        leaf: true
                                    }
                                ]
                            },
                            {
                                text: '用户管理',
                                id: 'm1_2',
                                leaf: true
                            }
                        ]
                    },
                    rootVisible: false,
                    listeners: {
                        itemclick: {
                            fn: me.onTreepanelItemClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    id: 'WorkspacePanel',
                    itemId: 'WorkspacePanel',
                    autoScroll: true,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'HomePanel',
                            itemId: 'HomePanel'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 27,
                    bodyStyle: 'background-color:#38B3EA;',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            height: 28,
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Copy Right'
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                boxready: {
                    fn: me.onViewportBoxReady,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onLogoffClick: function(button, e, eOpts) {
        Ext.create('MyApp.view.LoginWin').show();
        Ext.util.Cookies.clear('username');
        Ext.ComponentQuery.query('[id=name]')[0].setText('游客');
    },

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        //alert(record.getId());
        //var workspacePanel = this.child('#WorkspacePanel');
        //workspacePanel.layout.setActiveItem(record.getId());
        //workspacePanel.setTitle(record.getId());
    },

    onViewportBoxReady: function(component, width, height, eOpts) {
        var userName = Ext.util.Cookies.get("username");
        Ext.Ajax.request({     
            url:'/User/LoginValidate',  
            params:{  
                userName:  userName
            },  
            success: function(resp,opts) {   
                var respText = Ext.JSON.decode(resp.responseText);  
                if(respText.success){
                    Ext.ComponentQuery.query('[id=name]')[0].setText(Ext.util.Cookies.get("username"));
                }else{
                    Ext.create('MyApp.view.LoginWin').show(); 
                }
                //Ext.create('MyApp.view.LoginWin').show();  
            },   
            failure: function(resp,opts) {   
                Ext.create('MyApp.view.LoginWin').show(); 
            }     

        });


    }

});