/*
 * File: app/view/PortalAdv.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PortalAdv', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.portaladv',

    height: 372,
    width: 800,
    layout: {
        type: 'border'
    },
    title: '首页广告',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    store: 'PortalAdvStore',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        Ext.create('MyApp.view.AdvAdd', { closable: true, title: '新建广告' }).show();


                                    },
                                    icon: 'data/img/add1.png',
                                    text: '新建'
                                },
                                {
                                    xtype: 'button',
                                    margins: '0 10 0 10',
                                    icon: 'data/img/delete1.png',
                                    text: '删除',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    icon: 'data/img/zoom.gif',
                                    text: '查询',
                                    listeners: {
                                        click: {
                                            fn: me.onSearchBtnClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'advId',
                            text: 'AdvId'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'advertisingTitle',
                            text: '广告标题'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(value == '1'){
                                    return '头部广告';
                                }else if(value =='2'){
                                    return '中间广告';
                                }else if(value == '3'){
                                    return  '下部广告';
                                }
                            },
                            width: 63,
                            dataIndex: 'advType',
                            text: '广告类型'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 91,
                            dataIndex: 'shopId',
                            text: '关联店铺'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            dataIndex: 'power',
                            text: '权值'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 104,
                            dataIndex: 'content',
                            text: '广告体'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var max = 1;
                                if(value.length > max ){
                                    metaData.tdAttr = 'data-qtip="<img width=200px height=100px src= '+ value +' />"';
                                }

                                return value.length > max ? value : null;
                            },
                            width: 144,
                            dataIndex: 'pictureUrl',
                            text: '广告图片url'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'power',
                            text: 'Power'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                                return Ext.Date.format(new Date(Number(value.split('(')[1].split(')')[0])),'Y-m-d H:i')
                            },
                            width: 105,
                            dataIndex: 'addTime',
                            text: '开始时间'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                                return Ext.Date.format(new Date(Number(value.split('(')[1].split(')')[0])),'Y-m-d H:i')
                            },
                            width: 95,
                            dataIndex: 'endTime',
                            text: '结束时间'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.RowModel', {
                        listeners: {
                            selectionchange: {
                                fn: me.onRowModelSelectionChange,
                                scope: me
                            }
                        }
                    })
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var grid =  this.down('grid');

        var id = '';
        if(grid.getSelectionModel().selected.length>0){
            grid.getSelectionModel().selected.each(function(item){
                id+= item.get('advId');
            });


            Ext.Ajax.request( {
                url : '/Home/AdvDel',
                method : 'post',
                scope: this,
                params : {
                    id : id
                },
                success : function(response, options) {
                    this.down('grid').getStore().load();
                },
                failure : function() {

                }
            });

        }else{
            Ext.Msg.alert('提示','请选择记录！');
        }
    },

    onSearchBtnClick: function(button, e, eOpts) {
        var store = this.down('grid').getStore();
        store.load({
            callback:function(r, option, success){
                if(success){
                }else{
                    Ext.Msg.alert('错误',option.getError().statusText);
                }

            }});
    },

    onRowModelSelectionChange: function(model, selected, eOpts) {
        selected[0].data?Ext.ComponentQuery.query('portaladv form')[0].getForm().setValues(selected[0].data):undefined;
    }

});