/*
 * File: app/view/RecShopAdd.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RecShopAdd', {
    extend: 'Ext.window.Window',
    alias: 'widget.recshopadd',

    height: 133,
    width: 374,
    resizable: false,
    layout: {
        type: 'fit'
    },
    title: '推荐商铺修改',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: '类型',
                            name: 'type',
                            allowBlank: false,
                            editable: false,
                            hiddenName: 'type',
                            store: [
                                [
                                    '1',
                                    '胜利特价'
                                ],
                                [
                                    '2',
                                    '新店推荐'
                                ],
                                [
                                    '3',
                                    '会员商家'
                                ],
                                [
                                    '4',
                                    '品牌推荐'
                                ]
                            ]
                        },
                        {
                            xtype: 'button',
                            icon: 'data/img/save.gif',
                            text: '确认',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'id'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'shopId'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var form = this.down('form').getForm();
        var values = form.getValues();
        if(form.isValid()){
            form.submit({
                url:'/Manage/RecShopUpdate',
                params: values,
                method:'POST',
                scope: this,
                success:function(f,action) {
                    Ext.Msg.alert('提示:','成功');
                    this.close();
                    Ext.ComponentQuery.query('recshop')[0].down('grid').getStore().load();
                },
                failure:function(f,action){
                    Ext.Msg.alert(f,action);
                }
            });
        }
    }

});