/*
 * File: app/view/RoyaltyCard.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RoyaltyCard', {
    extend: 'Ext.form.Panel',
    alias: 'widget.royaltycard',

    border: false,
    id: 'RoyaltyCard',
    itemId: 'RoyaltyCard',
    width: 796,
    autoScroll: true,
    layout: {
        align: 'center',
        type: 'vbox'
    },
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'panel',
                    flex: 1,
                    dock: 'top',
                    border: false,
                    layout: {
                        type: 'column'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '10 0 0 0',
                            fieldLabel: 'Label',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '10 0 0 0',
                            fieldLabel: 'Label',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '10 0 0 0',
                            fieldLabel: 'Label',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '10 0 0 0',
                            fieldLabel: 'Label',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '10 0 0 0',
                            fieldLabel: 'Label',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '10 0 0 0',
                            fieldLabel: 'Label',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            margin: '10 0 0 0',
                            fieldLabel: 'Label',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Label',
                            labelAlign: 'right'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    dock: 'top',
                    width: 800,
                    layout: {
                        type: 'column'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 120,
                            margin: '10,0,0,0',
                            width: 490,
                            layout: {
                                type: 'column'
                            },
                            title: 'My Fields',
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '10,0,0,0',
                                    padding: '0 20 0 0',
                                    width: 80,
                                    fieldLabel: 'Label',
                                    labelWidth: 50
                                },
                                {
                                    xtype: 'radiofield',
                                    margin: '10,10,10,10',
                                    padding: '0 20 0 0',
                                    fieldLabel: '',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'radiofield',
                                    margin: '10,0,0,0',
                                    padding: '0 20 0 0',
                                    fieldLabel: '',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'radiofield',
                                    margin: '10,0,0,0',
                                    padding: '0 20 0 0',
                                    fieldLabel: '',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'radiofield',
                                    margin: '10,0,0,0',
                                    padding: '0 20 0 120',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'radiofield',
                                    margin: '10,0,0,0',
                                    padding: '0 20 0 0',
                                    fieldLabel: '',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'radiofield',
                                    margin: '10,0,0,0',
                                    boxLabel: 'Box Label'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 120,
                            margin: '10,0,0,0',
                            width: 201,
                            layout: {
                                type: 'column'
                            },
                            title: 'My Fields',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    padding: '10 0 0 0',
                                    fieldLabel: '',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'radiofield',
                                    padding: '10 0 0 10',
                                    fieldLabel: '',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'radiofield',
                                    padding: '10 0 0 0',
                                    fieldLabel: '',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'radiofield',
                                    padding: '10 0 0 10',
                                    fieldLabel: '',
                                    boxLabel: 'Box Label'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            margin: '10 30 0 20',
                            width: 633,
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'combobox',
                            margin: '10 0 0 20',
                            width: 411,
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'button',
                            margin: '10 0 0 20',
                            text: 'MyButton'
                        },
                        {
                            xtype: 'button',
                            margin: '10 0 0 20',
                            text: 'MyButton'
                        },
                        {
                            xtype: 'fieldset',
                            margin: '10 0 0 20',
                            width: 728,
                            layout: {
                                type: 'column'
                            },
                            title: '印税管理',
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    width: 264,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'button',
                                    margin: '10 0 0 20',
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'button',
                                    margin: '10 0 0 20',
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    width: 584,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'radiogroup',
                                    margin: '10 0 0 20',
                                    width: 263,
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Box Label'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Box Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 20',
                                    width: 207,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    width: 161,
                                    fieldLabel: 'Label'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            margin: '10 0 0 20',
                            width: 772,
                            layout: {
                                type: 'column'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    width: 304,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    width: 370,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 30 0 20',
                                    width: 300,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'radiogroup',
                                    margin: '10 0 0 20',
                                    width: 646,
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Box Label'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Box Label'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Box Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 20',
                                    width: 426,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 20',
                                    width: 425,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 20',
                                    width: 424,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 20',
                                    width: 347,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 50 0 20',
                                    width: 187,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    width: 168,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'label',
                                    margin: '10 0 0 10',
                                    text: '/'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    width: 57
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    width: 431,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 20',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 20',
                                    width: 223,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 63,
                                    margin: '10 0 0 20',
                                    width: 697,
                                    layout: {
                                        type: 'column'
                                    },
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            margin: '10 0 0 20',
                                            fieldLabel: '',
                                            boxLabel: 'Box Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '10 0 0 20',
                                            fieldLabel: 'Label',
                                            labelAlign: 'top'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '10 0 0 20',
                                            fieldLabel: 'Label',
                                            labelAlign: 'top'
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '20 0 0 20',
                                            text: 'MyButton'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    border: 2,
                                    height: 210,
                                    width: 772,
                                    layout: {
                                        type: 'column'
                                    },
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            fieldLabel: '',
                                            boxLabel: 'Box Label'
                                        },
                                        {
                                            xtype: 'radiogroup',
                                            margin: '10 0 0 20',
                                            width: 409,
                                            fieldLabel: '',
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    boxLabel: 'Box Label'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    boxLabel: 'Box Label'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    fieldLabel: '',
                                                    boxLabel: 'Box Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            height: 164,
                                            width: 578,
                                            layout: {
                                                type: 'column'
                                            },
                                            title: 'My Fields',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    width: 177,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'button',
                                                    margin: '0 0 0 20',
                                                    text: '寁嶼'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 177,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'button',
                                                    margin: '0 0 0 20',
                                                    text: 'MyButton'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 177,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'button',
                                                    margin: '0 0 0 20',
                                                    text: 'MyButton'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 177,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'button',
                                                    margin: '0 0 0 20',
                                                    text: 'MyButton'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 177,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 68,
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'button',
                                                    margin: '0 0 0 20',
                                                    text: 'MyButton'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    margin: '5 0 0 30',
                                                    fieldLabel: '',
                                                    boxLabel: 'Box Label'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    margin: '5 0 0 5',
                                                    width: 165,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'button',
                                                    margin: '5 0 0 5',
                                                    text: 'MyButton'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    margin: '5 0 0 5',
                                                    width: 203,
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 93,
                                    width: 772,
                                    layout: {
                                        type: 'column'
                                    },
                                    fieldLabel: '',
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            margin: '5 0 0 5',
                                            fieldLabel: 'Label',
                                            boxLabel: 'Box Label'
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '5 0 0 5',
                                            width: 178,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '5 0 0 5',
                                            text: 'MyButton'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '5 0 0 5',
                                            width: 195,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '5 0 0 5',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '5 0 0 5',
                                            width: 196,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '5 0 0 5',
                                            width: 186,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '5 0 0 5',
                                            width: 169,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '5 0 0 5',
                                            width: 164,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '5 0 0 5',
                                            width: 161,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '5 0 0 5',
                                            width: 159,
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 30,
                                    width: 728,
                                    layout: {
                                        type: 'column'
                                    },
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            margin: '5 0 0 5',
                                            width: 209,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'datefield',
                                            margin: '5 0 0 5',
                                            width: 203,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            margin: '5 0 0 5',
                                            fieldLabel: 'Label',
                                            boxLabel: 'Box Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 202,
                                    width: 772,
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            margin: '5 0 0 5',
                                            width: 563,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '5 0 0 5',
                                            width: 211,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '5 0 0 5',
                                            width: 565,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            margin: '5 0 0 5',
                                            width: 566,
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 120,
                                    width: 772,
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'button',
                                            margin: '5 0 0 5',
                                            text: 'MyButton'
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '5 0 0 5',
                                            text: 'MyButton'
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '5 0 0 5',
                                            text: 'MyButton'
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '5 0 0 5',
                                            text: 'MyButton'
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '5 0 0 5',
                                            text: 'MyButton'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});