/*
 * File: app/view/SearchPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SearchPanel', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.grid.plugin.CellEditing'
    ],

    border: false,
    height: 329,
    id: 'SearchPanel',
    itemId: 'SearchPanel',
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'ＰＰＴデータ入力',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'form',
                    flex: 1,
                    dock: 'top',
                    border: false,
                    height: 157,
                    layout: {
                        type: 'table'
                    },
                    bodyPadding: 10,
                    dockedItems: [
                        {
                            xtype: 'panel',
                            dock: 'left',
                            border: false,
                            height: 98,
                            id: 'buttonPanel',
                            margin: '',
                            style: 'text-align:right',
                            width: 120,
                            items: [
                                {
                                    xtype: 'button',
                                    margin: '20 30 0 0',
                                    width: 61,
                                    text: '取込'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            dock: 'left',
                            border: false,
                            height: 157,
                            id: 'FieldSetPanel',
                            width: 509,
                            layout: {
                                align: 'stretch',
                                pack: 'center',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    height: 136,
                                    layout: {
                                        type: 'column'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            margin: '10 0 0 0',
                                            fieldLabel: 'タイトルナンバー',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '10 0 0 0',
                                            width: 479,
                                            fieldLabel: 'タイトル名',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'datefield',
                                            margin: '10 0 0 0',
                                            width: 209,
                                            fieldLabel: '年月',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'label',
                                            margin: '13 0 0 0',
                                            text: ' ~ '
                                        },
                                        {
                                            xtype: 'datefield',
                                            margin: '10 0 0 0',
                                            width: 103
                                        },
                                        {
                                            xtype: 'datefield',
                                            margin: '10 0 0 0',
                                            width: 209,
                                            fieldLabel: '更新日',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'label',
                                            margin: '13 0 0 0',
                                            text: ' ~ '
                                        },
                                        {
                                            xtype: 'datefield',
                                            margin: '10 0 0 0',
                                            width: 103
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            dock: 'left',
                            border: false,
                            id: 'buttonPanel2',
                            maxWidth: 250,
                            minWidth: 200,
                            width: 204,
                            layout: {
                                type: 'column'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margin: '20 0 0 15',
                                    text: '一致検索'
                                },
                                {
                                    xtype: 'button',
                                    margin: '20 0 0 10',
                                    text: 'ＥＸＣＥＬ出力'
                                },
                                {
                                    xtype: 'button',
                                    margin: '20 0 0 15',
                                    text: '曖昧検索'
                                },
                                {
                                    xtype: 'button',
                                    margin: '20 0 0 10',
                                    text: 'ＰＤＦ出力'
                                },
                                {
                                    xtype: 'button',
                                    margin: '20 0 0 15',
                                    text: 'クリア'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            dock: 'left',
                            border: false,
                            width: 150
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    margins: '10 0 0 0',
                    border: false,
                    height: 136,
                    autoDestroy: false,
                    title: 'My Grid Panel',
                    store: 'gridStore',
                    plugins: [
                        Ext.create('Ext.grid.plugin.CellEditing', {

                        })
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtYearMonth',
                            text: '年月'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtTitleId',
                            text: 'タイトルナンバー'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 250,
                            dataIndex: 'txtTitleName',
                            text: 'タイトル名'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtHandlingFee',
                            text: 'ハンドリングフィー'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtTransactionFee',
                            text: 'トランザクションフィー'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtLeaseUpFee',
                            text: 'リースアップフィー'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtShopSales',
                            text: '店舗売上'
                        },
                        {
                            xtype: 'gridcolumn'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});