/*
 * File: app/view/ShopAdd.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ShopAdd', {
    extend: 'Ext.window.Window',

    height: 447,
    width: 419,
    resizable: false,
    layout: {
        type: 'fit'
    },
    title: '新增商铺',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    autoScroll: true,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '店铺名',
                            name: 'shopname',
                            allowBlank: false,
                            enforceMaxLength: true,
                            maxLength: 128
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: '用户',
                            name: 'userid',
                            allowBlank: false,
                            emptyText: '           <!--            请选择           --!>',
                            editable: false,
                            displayField: 'username',
                            hiddenName: 'userid',
                            store: 'UserListStore',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: '类型',
                            name: 'typeid',
                            allowBlank: false,
                            emptyText: '           <!--            请选择           --!>',
                            editable: false,
                            displayField: 'typeName',
                            hiddenName: 'typeid',
                            multiSelect: true,
                            store: 'TypeStore',
                            valueField: 'typeId'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '地址',
                            name: 'address',
                            enforceMaxLength: true,
                            maxLength: 200
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '邮箱',
                            name: 'email',
                            enforceMaxLength: true,
                            maxLength: 60,
                            vtype: 'email'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '电话',
                            name: 'tel',
                            enforceMaxLength: true,
                            maxLength: 11,
                            vtype: 'alphanum'
                        },
                        {
                            xtype: 'filefield',
                            width: 385,
                            fieldLabel: '商铺详细页图片',
                            name: 'shopdetailpic',
                            buttonText: '浏览...',
                            clearOnSubmit: false
                        },
                        {
                            xtype: 'filefield',
                            width: 385,
                            fieldLabel: '商铺列表页图片',
                            name: 'shoplistpic',
                            buttonText: '浏览...',
                            clearOnSubmit: false
                        },
                        {
                            xtype: 'filefield',
                            width: 385,
                            fieldLabel: '主页图片',
                            name: 'shoplogopic',
                            buttonText: '浏览...',
                            clearOnSubmit: false
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: '简介',
                            name: 'introduction',
                            enforceMaxLength: true,
                            maxLength: 300
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'column'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    icon: 'data/img/save.gif',
                                    text: '确认',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 0 0 20',
                                    icon: 'data/img/reset.gif',
                                    text: '重置',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick1,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var form = this.down('form').getForm();
        var values = form.getValues();
        var UserFilePath = this.down('form [name=shopdetailpic]').getValue();
        if(UserFilePath.length>0){
            if(!CheckFileExt(UserFilePath,/.jpg|.gif|.png|.bmp/i))
            {
                Ext.Msg.alert('错误','商铺详细页图片-您上传的文件不是图片类型，请重新选择！');
                return;
            }
        }
        UserFilePath = this.down('form [name=shoplistpic]').getValue();
        if(UserFilePath.length>0){
            if(!CheckFileExt(UserFilePath,/.jpg|.gif|.png|.bmp/i))
            {
                Ext.Msg.alert('错误','商铺列表页图片-您上传的文件不是图片类型，请重新选择！');
                return;
            }
        }
        UserFilePath = this.down('form [name=shoplogopic]').getValue();
        if(UserFilePath.length>0){
            if(!CheckFileExt(UserFilePath,/.jpg|.gif|.png|.bmp/i))
            {
                Ext.Msg.alert('错误','主页图片-您上传的文件不是图片类型，请重新选择！');
                return;
            }
        }
        if(form.isValid()){
            form.submit({
                url:"/Shop/ShopAdd",
                params: values,
                method:'POST',
                scope: this,
                success:function(f,action) {
                    Ext.Msg.alert('提示:','成功');
                    this.close();
                    Ext.ComponentQuery.query('shoplist grid')[0].getStore().load();
                },
                failure:function(f,action){
                    Ext.Msg.alert(f,action);
                }
            });
        }
        //判断是否是图片类型
        function CheckFileExt(extstr,exg)
        {
            var extstr = extstr.substring(extstr.lastIndexOf(".")).toLowerCase();
            if (extstr.match(exg) == null) {
                return false;
            }
            return true;
        }

    },

    onButtonClick1: function(button, e, eOpts) {
        this.up('form').getForm().reset();
    }

});