/*
 * File: app/view/UserManagement.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.UserManagement', {
    extend: 'Ext.panel.Panel',

    height: 372,
    id: 'userManagement',
    itemId: 'userManagement',
    width: 624,
    layout: {
        type: 'fit'
    },
    title: '用户管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'form',
                    dock: 'top',
                    id: 'userManagementSearchForm',
                    itemId: 'userManagementSearchForm',
                    layout: {
                        type: 'column'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'userName',
                            itemId: 'userName',
                            margin: '0 10 10 0',
                            fieldLabel: '姓名',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            id: 'userSSO',
                            itemId: 'userSSO',
                            margin: '0 10 10 0',
                            fieldLabel: '用户类别',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            id: 'userEmail',
                            itemId: 'userEmail',
                            margin: '0 10 10 0',
                            fieldLabel: '其他',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'combobox',
                            id: 'userDepartment',
                            itemId: 'userDepartment',
                            margin: '0 10 10 0',
                            fieldLabel: '部門',
                            labelAlign: 'right',
                            store: [
                                [
                                    '111',
                                    'Sales'
                                ],
                                [
                                    '222',
                                    'Product'
                                ],
                                [
                                    '333',
                                    'Marketing'
                                ],
                                [
                                    '444',
                                    'Finance'
                                ]
                            ]
                        },
                        {
                            xtype: 'combobox',
                            id: 'userStatus',
                            itemId: 'userStatus',
                            margin: '0 10 10 0',
                            fieldLabel: 'ステータス',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'checkboxfield',
                            id: 'searchFlag',
                            itemId: 'searchFlag',
                            margin: '0 0 10 30',
                            boxLabel: '模糊查询'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var form = this.up('form').getForm();
                                var userName = form.findField('userName').value;
                                var userSSO = form.findField('userSSO').value;
                                var userDepartment = form.findField('userDepartment').value;
                                var searchFlag = form.findField('searchFlag').value;
                                alert(userName+"   "+userSSO+"   "+userDepartment+"  "+searchFlag);
                            },
                            id: 'searchBtn',
                            itemId: 'searchBtn',
                            margin: '0 10 10 30',
                            icon: 'data/img/zoom.gif',
                            text: '检索'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                this.up('form').getForm().reset();
                            },
                            id: 'resetBtn',
                            itemId: 'resetBtn',
                            margin: '0 10 10 30',
                            icon: 'data/img/reset.gif',
                            text: '重置'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'userSearchResultGrid',
                    itemId: 'userSearchResultGrid',
                    store: 'UserList',
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'UserList'
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var centerContiner = Ext.getCmp('HomePanel');//WorkspacePanel
                                        var datagridPanel;
                                        datagridPanel = centerContiner.getComponent('UserAdd');
                                        alert("1");
                                        if (!datagridPanel) {
                                            alert("2");
                                            datagridPanel = Ext.create('MyApp.view.UserAdd', { closable: true, title: 'Add New User' });
                                            alert("3");
                                            centerContiner.add(datagridPanel);
                                        }

                                        centerContiner.setActiveTab(datagridPanel);
                                        datagridPanel.doLayout();
                                    },
                                    icon: 'data/img/add1.png',
                                    text: '新增'
                                },
                                {
                                    xtype: 'button',
                                    margins: '0 10 0 10',
                                    icon: 'data/img/delete1.png',
                                    text: '删除'
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'SSO',
                            text: 'SSO'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'UserName',
                            text: '姓名'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 180,
                            align: 'center',
                            dataIndex: 'EMail',
                            text: 'メール'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'ManagerSSO',
                            text: '上司SSO'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'UserId',
                            hideable: false,
                            text: 'UserId'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'Department',
                            text: '部門'
                        },
                        {
                            xtype: 'actioncolumn',
                            align: 'center',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var rec = record.get("SSO");
                                        alert(rec);
                                    },
                                    icon: 'data/img/forward.png'
                                },
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                        var id = record.get("UserId");
                                        alert(id);
                                    },
                                    icon: 'data/img/delete2.gif'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});