/*
 * File: app/controller/FrameController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.FrameController', {
    extend: 'Ext.app.Controller',

    views: [
        'MyViewport',
        'LoginWin'
    ],

    refs: [
        {
            ref: 'loginwin',
            selector: 'loginwin'
        }
    ],

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        var centerContiner = Ext.getCmp('HomePanel');//WorkspacePanel
        var datagridPanel;
        var menuId = record.getId();

        if(menuId=="m1_2"){    

            datagridPanel = MyApp.getApplication().getController("UserController").getUserlist();
            if (!datagridPanel) {
                datagridPanel = Ext.create('MyApp.view.UserManagement', { closable: true, title: '用户管理' });
                centerContiner.add(datagridPanel);
            }
        }

        else if(menuId=="m1_1_1"){    

            datagridPanel = MyApp.getApplication().getController("ShopController").getShoplist();
            if (!datagridPanel) {
                datagridPanel = Ext.create('MyApp.view.ShopManagement', { closable: true, title: '商铺管理' });
                centerContiner.add(datagridPanel);
            }
        }
        else if(menuId=="m1_1_2"){    

            datagridPanel = MyApp.getApplication().getController("ShopController").getRecshop();
            if (!datagridPanel) {
                datagridPanel = Ext.create('MyApp.view.RecShop', { closable: true, title: '推荐商铺' });
                centerContiner.add(datagridPanel);
            }
        }
        else if(menuId=="m1_1_3"){    

            datagridPanel = MyApp.getApplication().getController("PortalController").getPortaladv();
            if (!datagridPanel) {
                datagridPanel = Ext.create('MyApp.view.PortalAdv', { closable: true, title: '首页广告' });
                centerContiner.add(datagridPanel);
            }
        }
        else{    
            datagridPanel = centerContiner.getComponent('HomeTab');
        }

        centerContiner.setActiveTab(datagridPanel);
        //centerContiner.removeAll();
        //centerContiner.add(datagridPanel);
        datagridPanel.doLayout();
    },

    init: function(application) {
        this.control({
            "treepanel": {
                itemclick: this.onTreepanelItemClick
            }
        });
    }

});
